/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: besturkan (https://sketchfab.com/besturkan)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/poke-ball-e2d07e17cb7f4171a664f225eec8a251
Title: Poké Ball
*/

import { useGSAP } from '@gsap/react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useRef } from 'react'

function PokeBall(props) {
  const { nodes, materials } = useGLTF('models/poke_ball.glb')
  const pokeBallRef=useRef()
    useGSAP(()=>{
      gsap.to(pokeBallRef.current.position,{
          y:pokeBallRef.current.position.y+0.5,
          duration:1.5,
          repeat:-1,
          yoyo:true
      })
    })
  return (
    <group {...props} dispose={null} ref={pokeBallRef}>
      <group scale={0.01}>
        <group position={[62.104, 100.99, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_red_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_white_0.geometry}
            material={materials.white}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere001_balck_0.geometry}
            material={materials.balck}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002_light_0.geometry}
            material={materials.light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002_metal_0.geometry}
            material={materials.metal}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/poke_ball.glb')

export default PokeBall